Build and add links into header and footer blocks / #1
BreakFork/OCR_BLOG pull request #29
Opened 2019-02-19 14:33 UTC by BreakFork

2019-02-20 06:43 UTC, gahfy requested changes

2019-02-20 06:43 UTC, gahfy commented on Views/footer.html.twig
> +                <a class="nav-link" href="#">Sign In</a>
Pourquoi un sign-in ? Il ne doit être accessible que pour l'administration, et donc pas présent en lien pour les visiteurs

2019-02-20 06:43 UTC, gahfy commented on Views/footer.html.twig
> +                <a class="nav-link" href="#"><i class="fas fa-gavel"></i>&nbsp;&nbsp;Mentions légales</a>
Pourquoi deux espaces avant ?

2019-02-21 12:13 UTC, BreakFork commented on Views/footer.html.twig
> +                <a class="nav-link" href="#"><i class="fas fa-gavel"></i>&nbsp;&nbsp;Mentions légales</a>
Pour espacer 'Mentions légales' de la balise <i> située devant.

2019-02-21 12:33 UTC, gahfy requested changes

2019-02-21 12:33 UTC, gahfy commented on Views/footer.html.twig
> +                <a class="nav-link" href="#">Sign Up</a>
Ce lien est à enlever complètement. Il ne doit pas y avoir de lien accessible pour le visiteur

2019-02-21 12:48 UTC, merged