Create the view for getPostList /#38
BreakFork/OCR_BLOG pull request #39
Opened 2019-04-10 08:55 UTC by BreakFork

2019-04-10 13:06 UTC, gahfy requested changes

2019-04-10 13:06 UTC, gahfy commented on Models/Post.php
> +    public static function getPostList()
`public static function getPostList(): array`

2019-04-10 13:06 UTC, gahfy commented on Models/Post.php
> +     * @return array
Ça retourne quoi ?

2019-04-10 13:06 UTC, gahfy commented on Controllers/AdminController.php
> +        echo $this->render("admin/postList.html.twig", $postList);
Là tu as fait une belle boulette que tu pourras trouver tout seul.

2019-04-10 13:06 UTC, gahfy commented on Controllers/AdminController.php
> +         $postList = array(Post::getPostList());
`$postList = Post::getPostList();`

2019-04-10 13:28 UTC, BreakFork commented on Controllers/AdminController.php
> +        echo $this->render("admin/postList.html.twig", $postList);
LOL j'avais vu après...

2019-04-15 11:35 UTC, gahfy requested changes

2019-04-15 11:35 UTC, gahfy commented on Controllers/AdminController.php
> +         $postList = Post::getPostList();
Au temps pour moi, mais il ne manquerait pas comme un `$this->redirectToLoginIfNotConnected()` au début de chacune de tes méthodes de l'admin Controller ? :-)

2019-04-16 11:29 UTC, gahfy requested changes

2019-04-16 11:29 UTC, gahfy commented on Controllers/AdminController.php
> +        if (isset($_SESSION['user'])) {
NON !!! Ça existe déjà

2019-04-16 11:29 UTC, gahfy commented on Controllers/AdminController.php
> +        if (isset($_SESSION['user'])) {
NON !!! Ça existe déjà

2019-04-18 14:21 UTC, merged